build:
	g++ -std=c++17 -Wall ../AngryApp/*.cpp ../Physics/*.cpp ../Physics/Utils/*.cpp ../Physics/Objects/*.cpp -lm -lSDL2 -lSDL2_image -lSDL2_gfx -o angry_app

run:
	./angry_app

clean:
	rm angry_app
