build:
	g++ -std=c++17 -Wall ../Ragdoll/*.cpp ../Physics/*.cpp ../Physics/Utils/*.cpp ../Physics/Objects/*.cpp ../Physics/Logger/*.cpp ../Physics/Graphics/*.cpp -lm -lSDL2 -lSDL2_image -lSDL2_gfx -o ragdoll_app

run:
	./ragdoll_app

clean:
	rm ragdoll_app
