build:
	g++ -std=c++17 -Wall ../Chain/*.cpp ../Physics/*.cpp ../Physics/Utils/*.cpp ../Physics/Objects/*.cpp ../Physics/Logger/*.cpp ../Physics/Graphics/*.cpp -lm -lSDL2 -lSDL2_image -lSDL2_gfx -o chain_app

run:
	./chain_app

clean:
	rm chain_app
