build:
	g++ -std=c++17 -Wall ../FabricSimulation/*.cpp ../Physics/*.cpp ../Physics/Utils/*.cpp ../Physics/Objects/*.cpp -lm -lSDL2 -lSDL2_image -lSDL2_gfx -o fabric_app

run:
	./fabric_app

clean:
	rm fabric_app
