build:
	g++ -std=c++17 -Wall ../SoftBody/*.cpp ../Physics/*.cpp ../Physics/Utils/*.cpp ../Physics/Objects/*.cpp ../Physics/Logger/*.cpp ../Physics/Graphics/*.cpp -lm -lSDL2 -lSDL2_image -lSDL2_gfx -o softbody_app

run:
	./softbody_app

clean:
	rm softbody_app
